#!/usr/bin/env python3
"""
Regenerate references/16-pitfalls.md by collecting every chapter's Gotchas section.

Run after editing any chapter, so the one-page index never drifts from the
chapters it summarises.

    python scripts/build_pitfalls.py
"""
from __future__ import annotations

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REFS = os.path.join(os.path.dirname(HERE), 'references')
OUT = os.path.join(REFS, '16-pitfalls.md')

HEADER = """# 16 — Every pitfall, in one place

Generated by `scripts/build_pitfalls.py` from the `## Gotchas` section of each
chapter — do not edit by hand, edit the chapter.

Read this once before your first piece, and again when something is wrong and
you cannot hear why.

## The five that break the most pieces

1. **Channel folding.** Parts sharing an instrument land on one MIDI channel and
   cut each other's notes short. `midiio.write_midi(score, path, channels=[...])`.
2. **Percussion off channel 10** plays as a piano.
3. **`Dynamic` rescales velocities you set yourself** — `velocity=100` under a
   `Dynamic('pp')` renders at 50. Hairpins do nothing at all. Default is 90.
4. **Notes below an instrument's real range** render as synthetic mush.
   `verify.range_check`.
5. **You cannot listen, so measure** — chapter 15.

---
"""


def main() -> int:
    chapters = sorted(f for f in os.listdir(REFS)
                      if f.endswith('.md') and f != '16-pitfalls.md')
    out = [HEADER]
    total = 0
    for fn in chapters:
        text = open(os.path.join(REFS, fn)).read()
        m = re.search(r'^##+ *Gotchas.*?$(.*?)(?=^##? [^#]|\Z)', text,
                      re.M | re.S)
        if not m:
            continue
        body = m.group(1).strip()
        if not body:
            continue
        title = (re.search(r'^# (.+)$', text, re.M) or [None, fn])[1]
        n = len(re.findall(r'^\s*(?:[-*]|\d+\.)\s', body, re.M))
        total += n
        out.append(f'\n## {title}\n\n*from `{fn}` — {n} item(s)*\n\n{body}\n')
    out.insert(1, f'\n**{total} recorded pitfalls across {len(chapters)} chapters.**\n')
    with open(OUT, 'w') as f:
        f.write('\n'.join(out))
    print(f'wrote {OUT}: {total} pitfalls from {len(chapters)} chapters')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
